title: Shreya Rodda
#logo:
descrpition: A highly motivated Molecular Biology and Biotechnology student, seeking a challenging role where I can contribute to innovative research and developmental initiatives. 
show_downloads: false
theme: jekyll-theme-minimal
