title: Shreya Rodda
logo: /assets/img/github_photo-min
descrpition: A highly motivated Molecular Biology and Biotechnology student, with a proven academic and practical understanding of molecular biology techniques, eager to learn and apply my knowledge and skills in a dynamic professional setting. Seeking a challenging role where I can contribute to innovative research and developmental initiatives. 
show_downloads: true
theme: jekyll-theme-minimal
